### ISSUE TITLE
1.14.1 Unable to upgrade barrels 

### ISSUE THREAD

**Issue by Cardinite** [branchpanic/stockpile#55]
Adding a barrel to an anvil with a (vanilla) chest in the other slot has no output. Tried using a freshly crafted barrel, breaking a placed empty barrel, breaking a partially full barrel, and breaking a totally full barrel. Also tried saving, exiting, and re-opening the game as well as putting a barrel in the second slot and a chest in the first.

(Stockpile-1.0.4+1.14.1 / fabric-language-kotlin-1.3.30+build.2 / Minecraft 1.14.1 / MultiMC 5 - Version 0.6.5-1302)

**Comment by branchpanic** [comment]
Thanks for the thorough report! Unfortunately, most of Stockpile's documentation is out-of-date right now. The anvil upgrade system has been replaced by a more traditional item-based one since 1.0.0. If you have a recipe indexing mod like REI installed, take a look at the upgrade items Stockpile has.

I'm aware that with the current system there is a much lower max than before. Similar functionality will eventually return! I'll also take this as a cue to update the mod info soon.
