### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by BigCasper** [branchpanic/stockpile#58]
Mod crashes the game on launch with Fabric.
Latest Fabric, latest Stockpile as of 26.05.2019.

**Comment by branchpanic** [comment]
Thank you for opening an issue. If you could snag a crash log and post it to a website like Hastebin, that would be great.

Crashing on startup is often caused by missing dependencies. You mention you have the latest Fabric (which I assume means Fabric API) which is good. Have you installed [Fabric Language Kotlin](https://minecraft.curseforge.com/projects/fabric-language-kotlin/files) 1.3.30 or later?

**Comment by branchpanic** [comment]
I'll assume that this wasn't a problem with the mod itself since it hasn't been confirmed by anyone else. Feel free to continue discussion here if you're having issues.
