### ISSUE TITLE
I can't upgrade the barrels. Just a red cross over the arrow when i put in a barrel and a chest. why?

### ISSUE THREAD

**Issue by greenpk2** [branchpanic/stockpile#66]

**Comment by branchpanic** [comment]
The anvil upgrade system has been replaced by a more traditional one like in most other mods that add barrels. If you have REI installed, try searching for "upgrade" to see the upgrades Stockpile adds. The documentation has yet to be updated, and I apologize for the inconvenience. I simply haven't had time to work on this mod recently.

**Comment by greenpk2** [comment]
So I must get REI mod to be able to upgrade storage capacity now? :/

**Comment by greenpk2** [comment]
No other ways?

**Comment by branchpanic** [comment]
My bad, I just suggested using REI to search for and view the recipes of items Stockpile adds. The mod should work entirely on its own. The items you're looking for are the (Double) Capacity Upgrade and/or (Double) Multiplier Upgrade, which you can craft normally and then apply by right-clicking them on a barrel.

I'm aware this isn't really a great user experience as it relies on knowledge some other modded conventions that not everyone is familiar with. I'm working on a solution for this information to be available directly in the game, which is why I haven't updated it on most websites yet. Eventually you'll be able to just press a button with an item selected to be able to read this info without the need for REI.
