### ISSUE TITLE
mod incompat with tubular/stockpile with barrels and tube connectors

### ISSUE THREAD

**Issue by SDUBZ** [branchpanic/stockpile#82]
log:
http://puu.sh/E6XOL/36d059da34.log

**Comment by vini2003** [comment]
Stockpile apparently does not implement `getInvAvailableSlots()`, meaning Tubular doesn't know where to insert, thus inserting at a default inventory slot. I should probably just make it not work in such cases, but still, from my understanding, this should be fixed in Stockpile's SidedInventory implementation.

**Comment by branchpanic** [comment]
Thanks for the technical info. This should indeed be fixed in Stockpile. I've had trouble with the LibBlockAttributes wrapper I delegate Inventory to because, well, I'm kind of abusing it to get the result I want. I'll see if I can come up with something cleaner as soon as I get the chance.

**Comment by vini2003** [comment]
After further investigation it seems like somehow the filter option in Tubular is broken as of last release. How this got past testing is beyond me.

Put this on hold for now as I try to fix this.

**Comment by branchpanic** [comment]
Will do, good luck and keep me updated if there's anything I should do on my part to make things easier.

**Comment by SDUBZ** [comment]
thank you guys for all your hard work i appreciate so much :D

**Comment by vini2003** [comment]
Rewrite finished, though LibGUI version update was necessary and I had to update to 19w36a. As such, I can't _really_ fix this right now.

Whenever 1.15 is released and we both update to it, it'll be fixed. I don't really feel like bothering the LibGUI guys with backporting new features to 1.14 just for Tubular.

**Comment by SDUBZ** [comment]
oh so i gotta wait until 1.15 :(

**Comment by vini2003** [comment]
I'll be fair, that tomorrow has been taking quite a while, though I am still working on a similar thing - in specific, [Buffer](https://github.com/vini2003/Buffer), whose aim is to expose a single stack and keep the rest in an internal buffer of a special inventory type. It's been quite a ride so far given I, to say the least, suck at this right now.

**Comment by branchpanic** [comment]
That's awesome! You're of course free to reference any of Stockpile's code if it helps in any way. FWIW I've been considering relicensing as public domain by major version 2 or something like that since I clearly don't have enough time to maintain it.

Also if you ever separate out your new inventory code into a library or something like that I'd be happy to contribute to it and/or use it for Stockpile. I think having a consistent abstraction for buffer/mass storage inventories would be beneficial so mods that aren't dedicated to storage can get creative with them. All in all i suck at this too so don't worry about it 😉

**Comment by vini2003** [comment]
It's been a while!

Buffer has been [released](https://www.curseforge.com/minecraft/mc-mods/buffer) and seems to be working relatively well aside an issue with voiding that I'll solve whenever I finish my GUI library,

I have discontinued Tubular because I've learned a lot since then and can probably make it work much better, so don't worry about this issue anymore.

**Comment by SDUBZ** [comment]
@vini2003 why you stop work on something like logistical pipes :O

**Comment by branchpanic** [comment]
Glad things have gone well and good luck with Buffer! I'll close this issue now since it seems like we've figured everything out.
