### ISSUE TITLE
I accidentally stored 3 backpacks in a barrel, now I have 3 identical backpacks

### ISSUE THREAD

**Issue by calloatti** [branchpanic/stockpile#83]
![2019-08-19_14 05 22](https://user-images.githubusercontent.com/12817862/63284718-9013c180-c28a-11e9-9896-b9c0169c074a.png)

I right clicked accidentally in an empty barrel with one of my backpacks, all 3 of my backpacks with different content were stored in the barrel. When I took them out, I got 3 duplicate backpacks. Backpack 2 and 3 are gone forever, and now I have three backpacks 1.

https://www.curseforge.com/minecraft/mc-mods/mpcs-backpacks

**Comment by branchpanic** [comment]
Thanks for your report. I have a feeling this has been fixed in dev but I'll make sure to double check. Regardless, I'll aim to resolve it in the next patch release.

**Comment by branchpanic** [comment]
1.1.0 is being updated to Twitch and should fix this. I'd just back up your world before upgrading since I also rewrote some internals (in a backwards-compatible manner) and, while in my testing everything seems to be working fine, it's possible I missed something due to how much I've had going on. Feel free to continue discussion here if you run into more NBT-related issues
