### ISSUE TITLE
(non-urgent) 19w46b/1.15 snapshots

### ISSUE THREAD

**Issue by Yoghurt4C** [branchpanic/stockpile#90]
unless it's not in your interests to pursue snapshot releases, stockpile very happily crashes on startup, and I've no doubt this one crashlog is just the first thing caught by loader
https://pastebin.com/HBmaVqPM

**Comment by branchpanic** [comment]
Thanks for the report. I'll see what I can do this weekend, I haven't really been up-to-date on the whole Fabric thing for a few months now so something probably changed, and I wouldn't be surprised if it's a simple fix.

**Comment by branchpanic** [comment]
Ok well I lied about it being last weekend sorry about that... I definitely should focus a bit on this more because it looks like there are some changes that will definitely matter for 1.15 and I'd certainly like the mod to at least work even if I'm not super-actively maintaining it. Next update you hear from me in this thread will hopefully be a new version.

**Comment by Yoghurt4C** [comment]
🙂

**Comment by branchpanic** [comment]
☹️ 

I don't even have an excuse this time. There were a ton of rendering changes that I've been struggling to understand, and now finals are happening. Barrels work but I can't get the front display to actually show up. It looks like 1.15 is out now so I'll target that when I get to it...

**Comment by Yoghurt4C** [comment]
could've just asked on fabricord and saved yourself a headache

**Comment by branchpanic** [comment]
Updated. Thank you for your patience.
https://www.curseforge.com/minecraft/mc-mods/stockpile/files/2846959

**Comment by Yoghurt4C** [comment]
where am I? who is this
